# Generated by Django 4.2.5 on 2024-02-08 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawapp', '0002_request_delete_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
