# Generated by Django 4.2.5 on 2024-02-11 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawapp', '0003_request_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='request',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
