# Generated by Django 4.2.5 on 2024-02-17 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lawapp', '0005_alter_request_role_case'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('morning_start', models.CharField(choices=[('6', '06:00'), ('7', '07:00'), ('8', '08:00'), ('9', '09:00'), ('10', '10:00'), ('11', '11:00'), ('12', '12:00')], default='06:00', max_length=5)),
                ('morning_end', models.CharField(choices=[('6', '06:00'), ('7', '07:00'), ('8', '08:00'), ('9', '09:00'), ('10', '10:00'), ('11', '11:00'), ('12', '12:00')], default='12:00', max_length=5)),
                ('afternoon_start', models.CharField(choices=[('12', '12:00'), ('13', '13:00'), ('14', '14:00'), ('15', '15:00'), ('16', '16:00')], default='12:00', max_length=5)),
                ('afternoon_end', models.CharField(choices=[('12', '12:00'), ('13', '13:00'), ('14', '14:00'), ('15', '15:00'), ('16', '16:00')], default='16:00', max_length=5)),
                ('evening_start', models.CharField(choices=[('16', '16:00'), ('17', '17:00'), ('18', '18:00'), ('19', '19:00'), ('20', '20:00'), ('21', '21:00'), ('22', '22:00')], default='16:00', max_length=5)),
                ('evening_end', models.CharField(choices=[('16', '16:00'), ('17', '17:00'), ('18', '18:00'), ('19', '19:00'), ('20', '20:00'), ('21', '21:00'), ('22', '22:00')], default='22:00', max_length=5)),
                ('appointment_duration', models.PositiveSmallIntegerField(choices=[(15, '15 minutes'), (30, '30 minutes'), (45, '45 minutes'), (60, '1 hour')], default=15)),
                ('advocate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
