# Generated by Django 4.2.5 on 2024-02-22 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawapp', '0006_setappointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setappointment',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
