# Generated by Django 4.2.5 on 2024-02-22 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawapp', '0008_alter_setappointment_afternoon_end_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setappointment',
            old_name='date',
            new_name='from_date',
        ),
        migrations.AddField(
            model_name='setappointment',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
