# Generated by Django 4.2.5 on 2024-02-25 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lawapp', '0009_rename_date_setappointment_from_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setappointment',
            name='afternoon_end',
            field=models.CharField(blank=True, choices=[('12:00', '12:00'), ('13:00', '13:00'), ('14:00', '14:00'), ('15:00', '15:00'), ('16:00', '16:00')], default='16:00', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='setappointment',
            name='afternoon_start',
            field=models.CharField(blank=True, choices=[('12:00', '12:00'), ('13:00', '13:00'), ('14:00', '14:00'), ('15:00', '15:00'), ('16:00', '16:00')], default='12:00', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='setappointment',
            name='evening_end',
            field=models.CharField(blank=True, choices=[('16:00', '16:00'), ('17:00', '17:00'), ('18:00', '18:00'), ('19:00', '19:00'), ('20:00', '20:00'), ('21:00', '21:00'), ('22:00', '22:00')], default='22:00', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='setappointment',
            name='evening_start',
            field=models.CharField(blank=True, choices=[('16:00', '16:00'), ('17:00', '17:00'), ('18:00', '18:00'), ('19:00', '19:00'), ('20:00', '20:00'), ('21:00', '21:00'), ('22:00', '22:00')], default='16:00', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='setappointment',
            name='morning_end',
            field=models.CharField(blank=True, choices=[('06:00', '06:00'), ('07:00', '07:00'), ('08:00', '08:00'), ('09:00', '09:00'), ('10:00', '10:00'), ('11:00', '11:00'), ('12:00', '12:00')], default='12:00', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='setappointment',
            name='morning_start',
            field=models.CharField(blank=True, choices=[('06:00', '06:00'), ('07:00', '07:00'), ('08:00', '08:00'), ('09:00', '09:00'), ('10:00', '10:00'), ('11:00', '11:00'), ('12:00', '12:00')], default='06:00', max_length=5, null=True),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_slot', models.CharField(max_length=25)),
                ('phone_number', models.CharField(max_length=15)),
                ('appointment_type', models.CharField(choices=[('in_office', 'In-Office'), ('phone', 'Phone')], max_length=10)),
                ('advocate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advocate_appointments', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_appointments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
