# Generated by Django 4.2.5 on 2024-03-06 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawapp', '0012_remove_updates_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time_slot',
            field=models.CharField(choices=[('8:00 - 8:30', '8:00 - 8:30'), ('8:30 - 9:00', '8:30 - 9:00'), ('9:00 - 9:30', '9:00 - 9:30'), ('9:30 - 10:00', '9:30 - 10:00'), ('10:00 - 10:30', '10:00 - 10:30'), ('10:30 - 11:00', '10:30 - 11:00'), ('11:00 - 11:30', '11:00 - 11:30'), ('11:30 - 12:00', '11:30 - 12:00'), ('12:00 - 12:30', '12:00 - 12:30'), ('12:30 - 13:00', '12:30 - 13:00'), ('14:00 - 14:30', '14:00 - 14:30'), ('14:30 - 15:00', '14:30 - 15:00'), ('15:00 - 15:30', '15:00 - 15:30'), ('15:30 - 16:00', '15:30 - 16:00'), ('16:00 - 16:30', '16:00 - 16:30'), ('16:30 - 17:00', '16:30 - 17:00')], max_length=25),
        ),
    ]
