# Generated by Django 4.2.5 on 2024-03-16 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawapp', '0017_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
