# Generated by Django 4.2.5 on 2024-03-18 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawapp', '0019_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
