# Generated by Django 5.1.6 on 2025-03-05 10:13

from django.db import migrations

def create_user_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    group_names = ["advocate", "client", "admin"]
    
    for name in group_names:
        Group.objects.get_or_create(name=name)

class Migration(migrations.Migration):

    dependencies = [
        ('lawapp', '0021_alter_advocatedetails_category'),
    ]

    operations = [
        migrations.RunPython(create_user_groups),
    ]
